name: Install Dependencies via MSBuild
description: Install dependencies using MSBuild

inputs:
  msbuild-dependency-target:
    default: "CKANInstall"
    description: msbuild target to install dependencies
  solution-file-path:
    description: path to the .sln file

runs:
  using: composite
  steps:
    - name: Run MSBuild Dependency Target
      if: inputs.msbuild-dependency-target != ''
      shell: bash
      working-directory: ${{ github.workspace }}
      run: dotnet msbuild -t:${{ inputs.msbuild-dependency-target }} ${{ inputs.solution-file-path }}

    - name: Debug
      if: env.ACTIONS_STEP_DEBUG
      shell: bash
      run: |
        ls -R ${{ env.KSPRoot }}/GameData
        echo "${{ toJson(env) }}"
        echo "${{ toJson(github )}}"
        echo "${{ toJson(job) }}"
        echo "${{ toJson(steps) }}"
