name: assemble-release

inputs:
  artifacts:
    description: Space-separated list of file globs to include in the output artifact
    default: GameData LICENSE* README* CHANGELOG*
  output-file-name:
    description: Output artifact name
    default: ${{ github.event.repository.name || 'release'}}

outputs:
  artifact-id:
    value: ${{ steps.upload-artifact.outputs.artifact-id }}
  artifact-url:
    value: ${{ steps.upload-artifact.outputs.artifact-url }}

runs:
  using: composite
  steps:
    - name: Set RELEASE_STAGING
      if: ${{ !env.RELEASE_STAGING}}
      shell: bash
      run: echo 'KSP_ROOT=${{ '/tmp/release' }}' >> "$GITHUB_ENV"

    - name: Assemble Release
      shell: bash
      run: |
        mkdir -p ${{ env.RELEASE_STAGING  }}
        # TODO: delete pdb files?  run some kind of assembly script?
        cp -r -v ${{ inputs.artifacts }} ${{ env.RELEASE_STAGING }} || :
        cd ${{ env.RELEASE_STAGING }}
        zip -r ${{ github.workspace }}/${{ inputs.output-file-name }}.zip .
        echo 'ARTIFACT_FILENAME=${{ inputs.output-file-name }}' >> $GITHUB_ENV

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.RELEASE_STAGING }}
        name: ${{ inputs.output-file-name }}
        if-no-files-found: error
