name: build

on:
  push:
    branches: [ $default-branch ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./KSPBuildTools/.github/workflows/build.yml
    with:
      ksp-zip-url: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip
