name: build
description: Build and assemble a KSP mod that uses csproj file.

on:
  push:
    branches: [ $default-branch ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

env:
  KSPRoot: /tmp/ksp
  RELEASE_STAGING: /tmp/release
  
jobs:
  build:
    steps:
      - name: Checkout Mod Repo
        uses: actions/checkout@v4
        with:
            submodules: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.x

      # Install CKAN and set up an instance. If CKAN is not needed, remove this step
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/ckan-setup@main
        with:
          # Any additional CKAN identifiers not listed in the csproj can be listed here. space-separated 
          dependency-identifiers: "" 
      
      # Install any CKAN dependencies listed in the msbuild file. If there are none, remove this step
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main

      # Compile the mod. 
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@main
        with:
          ksp-zip-url: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip
          ksp-zip-password: ${{ secrets.ksp-zip-password }}

      # Assemble the mod into a release package and upload it as an artifact
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main
        with:
          artifacts: "GameData LICENSE* README* CHANGELOG*"
          output-file-name: ${{ github.event.repository.name }}-${{ inputs.build-configuration }}