name: publish-to-spacedock

inputs:
  spacedock-username:
    description: Spacedock login username
    default: ${{ env.SPACEDOCK_USERNAME }}
  spacedock-password:
    description: Spacedock login password. Store this as a secret!
    default: ${{ env.SPACEDOCK_PASSWORD }}
  game-id:
    description: ID of the game we are deploying for. This should probably be left as-is for KSP 1.
    default: '3102' # hardcoded to KSP1 gameid.  retrieve from https://spacedock.info/api/games
  mod-id:
    description: ID of the mod we are deploying. Get this from the end of your mod's spacedock URL
    default: ${{ env.SPACEDOCK_MOD_ID }}

runs:
  using: composite
  steps:
    - name: get-release-info
      shell: bash
      env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      run: |
        gh release view --json assets,body,tagName > release.json
        echo ARTIFACT_FILENAME=$(jq -r '.assets[0].name' release.json) >> $GITHUB_ENV
        echo RELEASE_NOTES=$(jq -r .body release.json) >> $GITHUB_ENV
        RELEASE_TAG=$(jq -r .tagName release.json)
        echo VERSION_STRING=$RELEASE_TAG >> $GITHUB_ENV
        gh release download $RELEASE_TAG

    - name: test
      shell: bash
      run:
        printenv

    - name: upload-to-spacedock
      if: false
      uses: KSP2Community/spacedock-upload@v1.0.0
      with:
        username: ${{ inputs.spacedock-username }}
        password: ${{ inputs.spacedock-password }}
