name: build

on:
  workflow_call:
    inputs:
      build-configuration:
        type: string
        default: Release
      artifacts:
        type: string
        default: GameData LICENSE* README* CHANGELOG*
      ksp-zip-url:
        type: string
        default: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip
      dependency-identifiers:
        type: string
      msbuild-dependency-target:
        default: CKANInstall
        type: string
      solution-file-path:
        type: string
    secrets:
      ksp-zip-password:
        required: false

env:
  KSPRoot: /tmp/ksp
  RELEASE_STAGING: /tmp/release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mod Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.x

      # Install CKAN and set up an instance. If CKAN is not needed, remove this step
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/ckan-setup@main
        with:
          dependency-identifiers: ${{ inputs.dependency-identifiers }}

      # Install any CKAN dependencies listed in the msbuild file. If there are none, remove this step
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
        with:
          msbuild-dependency-target: ${{ inputs.msbuild-dependency-target }}
          solution-file-path: ${{ inputs.solution-file-path }}

      # Compile the mod.
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@main
        with:
          build-configuration: ${{ inputs.build-configuration }}
          ksp-zip-url: ${{ inputs.ksp-zip-url }}
          ksp-zip-password: ${{ secrets.ksp-zip-password }}

      # Assemble the mod into a release package and upload it as an artifact
      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main
        with:
          artifacts: ${{ inputs.artifacts }}
          output-file-name: ${{ github.event.repository.name }}-${{ inputs.build-configuration }}