name: build

on:
  workflow_call:
    inputs:
      build-configuration:
        type: string
        default: Release
      artifacts:
        type: string
        default: GameData LICENSE* README* CHANGELOG*
      ksp-zip-url:
        type: string
        default: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip
      dependency-identifiers:
        type: string
      msbuild-dependency-target:
        type: string
      solution-file-path:
        type: string
    secrets:
      ksp-zip-password:
        required: false

env:
  KSPRoot: /tmp/ksp
  RELEASE_STAGING: /tmp/release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mod Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: compile
        uses: ./.github/actions/compile
        with:
          build-configuration: ${{ inputs.build-configuration }}
          ksp-zip-url: ${{ inputs.ksp-zip-url }}
          ksp-zip-password: ${{ secrets.ksp-zip-password }}
          dependency-identifiers: ${{ inputs.dependency-identifiers }}
          msbuild-dependency-target: ${{ inputs.msbuild-dependency-target }}
          solution-file-path: ${{ inputs.solution-file-path }}

      - name: assemble-release
        uses: ./.github/actions/assemble-release
        with:
          artifacts: ${{ inputs.artifacts }}
          output-file-name: ${{ github.event.repository.name }}-${{ inputs.build-configuration }}
