# playground for ckan
# this workflow isnt very useful on its own except as a testbed for the install-dependencies action

name: ckan

on:
  workflow_dispatch

defaults:
  run:
    shell: bash

env:
  KSPRoot: /tmp/ksp

jobs:
  ckan:
    runs-on: ubuntu-latest
    steps:
      - name: install-dependencies
        uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
        with:
          dependency-identifiers: |
            ModuleManager
            MoneroFlags
      
