name: test plugin mod build

on:
  workflow_call:

env:
 TESTDIR: tests/plugin-mod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: ./.github/actions/setup-ckan

      - uses: ./.github/actions/compile
        with:
          solution-file-path: ${{ env.TESTDIR }}/mymod.csproj
          ksp-zip-url: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip

      - uses: ./.github/actions/assemble-release
        with:
          artifacts: ${{ env.TESTDIR }}/GameData ${{ env.TESTDIR }}/mymod.csproj
          output-file-name: plugin-mod
